In [1]:
import pandas as pd

df = pd.read_csv("../data/graduation_dataset.csv")

#print(df.head)

#print("Antall rader og kolonner:")
#print(df.shape)
#print(df.columns)

print("Informasjon:")
#print(df.info())
#print(df.describe())


print("Manglende verdier:")
print(df.isna().sum())

Informasjon:
Manglende verdier:
Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nationality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  0
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               0
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  0
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

In [2]:
# Dataset dimensions
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

# First five rows
display(df.head())

Rows: 4424
Columns: 35

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Nationality,Mother's qualification,Father's qualification,Mother's occupation,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,8,5,2,1,1,1,13,10,6,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,6,1,11,1,1,1,1,3,4,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,5,1,1,1,22,27,10,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,8,2,15,1,1,1,23,27,6,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,12,1,3,0,1,1,22,28,10,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [3]:
# Data type and non-null count for every column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance                      4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Nationality                                     4424 non-null   int64
 7   Mother's qualification                          4424 non-null   int64
 8   Father's qualification                          4424 non-null   int64
 9   Mother's occupation                             4424 non-null   int64
 10  Father's occupation                             4424 non-null   int64
 11  Displaced                                       4424 non-null   int64
 12  Educational special needs                       4424 non-null   int64
 13  Debtor                                          4424 non-null   int64
 14  Tuition fees up to date                         4424 non-null   int64
 15  Gender                                          4424 non-null   int64
 16  Scholarship holder                              4424 non-null   int64
 17  Age at enrollment                               4424 non-null   int64
 18  International                                   4424 non-null   int64
 19  Curricular units 1st sem (credited)             4424 non-null   int64
 20  Curricular units 1st sem (enrolled)             4424 non-null   int64
 21  Curricular units 1st sem (evaluations)          4424 non-null   int64
 22  Curricular units 1st sem (approved)             4424 non-null   int64
 23  Curricular units 1st sem (grade)                4424 non-null   float64
 24  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 25  Curricular units 2nd sem (credited)             4424 non-null   int64
 26  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 27  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 28  Curricular units 2nd sem (approved)             4424 non-null   int64
 29  Curricular units 2nd sem (grade)                4424 non-null   float64
 30  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 31  Unemployment rate                               4424 non-null   float64
 32  Inflation rate                                  4424 non-null   float64
 33  GDP                                             4424 non-null   float64
 34  Target                                          4424 non-null   str
dtypes: float64(5), int64(29), str(1)
memory usage: 1.2 MB

In [4]:
# Summary statistics for both numerical and categorical columns
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Marital status,4424.0,NaN,NaN,NaN,1.178571,0.605747,1.0,1.0,1.0,1.0,6.0
Application mode,4424.0,NaN,NaN,NaN,6.88698,5.298964,1.0,1.0,8.0,12.0,18.0
Application order,4424.0,NaN,NaN,NaN,1.727848,1.313793,0.0,1.0,1.0,2.0,9.0
Course,4424.0,NaN,NaN,NaN,9.899186,4.331792,1.0,6.0,10.0,13.0,17.0
Daytime/evening attendance,4424.0,NaN,NaN,NaN,0.890823,0.311897,0.0,1.0,1.0,1.0,1.0
Previous qualification,4424.0,NaN,NaN,NaN,2.53142,3.963707,1.0,1.0,1.0,1.0,17.0
Nationality,4424.0,NaN,NaN,NaN,1.254521,1.748447,1.0,1.0,1.0,1.0,21.0
Mother's qualification,4424.0,NaN,NaN,NaN,12.322107,9.026251,1.0,2.0,13.0,22.0,29.0
Father's qualification,4424.0,NaN,NaN,NaN,16.455244,11.0448,1.0,3.0,14.0,27.0,34.0
Mother's occupation,4424.0,NaN,NaN,NaN,7.317812,3.997828,1.0,5.0,6.0,10.0,32.0
Father's occupation,4424.0,NaN,NaN,NaN,7.819168,4.856692,1.0,5.0,8.0,10.0,46.0
Displaced,4424.0,NaN,NaN,NaN,0.548373,0.497711,0.0,0.0,1.0,1.0,1.0
Educational special needs,4424.0,NaN,NaN,NaN,0.011528,0.10676,0.0,0.0,0.0,0.0,1.0
Debtor,4424.0,NaN,NaN,NaN,0.113698,0.31748,0.0,0.0,0.0,0.0,1.0
Tuition fees up to date,4424.0,NaN,NaN,NaN,0.880651,0.324235,0.0,1.0,1.0,1.0,1.0
Gender,4424.0,NaN,NaN,NaN,0.351718,0.47756,0.0,0.0,0.0,1.0,1.0
Scholarship holder,4424.0,NaN,NaN,NaN,0.248418,0.432144,0.0,0.0,0.0,0.0,1.0
Age at enrollment,4424.0,NaN,NaN,NaN,23.265145,7.587816,17.0,19.0,20.0,25.0,70.0
International,4424.0,NaN,NaN,NaN,0.024864,0.155729,0.0,0.0,0.0,0.0,1.0
Curricular units 1st sem (credited),4424.0,NaN,NaN,NaN,0.709991,2.360507,0.0,0.0,0.0,0.0,20.0
Curricular units 1st sem (enrolled),4424.0,NaN,NaN,NaN,6.27057,2.480178,0.0,5.0,6.0,7.0,26.0
Curricular units 1st sem (evaluations),4424.0,NaN,NaN,NaN,8.299051,4.179106,0.0,6.0,8.0,10.0,45.0
Curricular units 1st sem (approved),4424.0,NaN,NaN,NaN,4.7066,3.094238,0.0,3.0,5.0,6.0,26.0
Curricular units 1st sem (grade),4424.0,NaN,NaN,NaN,10.640822,4.843663,0.0,11.0,12.285714,13.4,18.875
Curricular units 1st sem (without evaluations),4424.0,NaN,NaN,NaN,0.137658,0.69088,0.0,0.0,0.0,0.0,12.0
Curricular units 2nd sem (credited),4424.0,NaN,NaN,NaN,0.541817,1.918546,0.0,0.0,0.0,0.0,19.0
Curricular units 2nd sem (enrolled),4424.0,NaN,NaN,NaN,6.232143,2.195951,0.0,5.0,6.0,7.0,23.0
Curricular units 2nd sem (evaluations),4424.0,NaN,NaN,NaN,8.063291,3.947951,0.0,6.0,8.0,10.0,33.0
Curricular units 2nd sem (approved),4424.0,NaN,NaN,NaN,4.435805,3.014764,0.0,2.0,5.0,6.0,20.0
Curricular units 2nd sem (grade),4424.0,NaN,NaN,NaN,10.230206,5.210808,0.0,10.75,12.2,13.333333,18.571429
Curricular units 2nd sem (without evaluations),4424.0,NaN,NaN,NaN,0.150316,0.753774,0.0,0.0,0.0,0.0,12.0
Unemployment rate,4424.0,NaN,NaN,NaN,11.566139,2.66385,7.6,9.4,11.1,13.9,16.2
Inflation rate,4424.0,NaN,NaN,NaN,1.228029,1.382711,-0.8,0.3,1.4,2.6,3.7
GDP,4424.0,NaN,NaN,NaN,0.001969,2.269935,-4.06,-1.7,0.32,1.79,3.51
Target,4424,3,Graduate,2209,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
missing_values = pd.DataFrame({
    "Missing values": df.isna().sum(),
    "Missing percentage": (df.isna().mean() * 100).round(2)
})

display(missing_values.sort_values("Missing values", ascending=False))

,Missing values,Missing percentage
Marital status,0,0.0
Application mode,0,0.0
Application order,0,0.0
Course,0,0.0
Daytime/evening attendance,0,0.0
Previous qualification,0,0.0
Nationality,0,0.0
Mother's qualification,0,0.0
Father's qualification,0,0.0
Mother's occupation,0,0.0
Father's occupation,0,0.0
Displaced,0,0.0
Educational special needs,0,0.0
Debtor,0,0.0
Tuition fees up to date,0,0.0
Gender,0,0.0
Scholarship holder,0,0.0
Age at enrollment,0,0.0
International,0,0.0
Curricular units 1st sem (credited),0,0.0
Curricular units 1st sem (enrolled),0,0.0
Curricular units 1st sem (evaluations),0,0.0
Curricular units 1st sem (approved),0,0.0
Curricular units 1st sem (grade),0,0.0
Curricular units 1st sem (without evaluations),0,0.0
Curricular units 2nd sem (credited),0,0.0
Curricular units 2nd sem (enrolled),0,0.0
Curricular units 2nd sem (evaluations),0,0.0
Curricular units 2nd sem (approved),0,0.0
Curricular units 2nd sem (grade),0,0.0
Curricular units 2nd sem (without evaluations),0,0.0
Unemployment rate,0,0.0
Inflation rate,0,0.0
GDP,0,0.0
Target,0,0.0

In [8]:
categorical_columns = [
    "Marital status",
    "Application mode",
    "Course",
    "Daytime/evening attendance",
    "Previous qualification",
    "Nationality",
    "Mother's qualification",
    "Father's qualification",
    "Mother's occupation",
    "Father's occupation",
    "Displaced",
    "Educational special needs",
    "Debtor",
    "Tuition fees up to date",
    "Gender",
    "Scholarship holder",
    "International",
    "Target"
]

unique_summary = pd.DataFrame({
    "Number of unique values": df[categorical_columns].nunique(),
    "Unique values": [
        df[column].dropna().unique().tolist()
        for column in categorical_columns
    ]
})

display(unique_summary)

,Number of unique values,Unique values
Marital status,6,"[1, 2, 4, 3, 5, 6]"
Application mode,18,"[8, 6, 1, 12, 9, 17, 15, 16, 14, 4, 13, 7, 3, ..."
Course,17,"[2, 11, 5, 15, 3, 17, 12, 10, 14, 16, 6, 8, 13..."
Daytime/evening attendance,2,"[1, 0]"
Previous qualification,17,"[1, 12, 16, 14, 8, 3, 15, 2, 4, 9, 17, 11, 6, ..."
Nationality,21,"[1, 15, 3, 14, 12, 18, 5, 11, 8, 17, 4, 9, 13,..."
Mother's qualification,29,"[13, 1, 22, 23, 3, 4, 27, 2, 19, 10, 25, 7, 5,..."
Father's qualification,34,"[10, 3, 27, 28, 1, 14, 5, 4, 24, 2, 29, 9, 7, ..."
Mother's occupation,32,"[6, 4, 10, 8, 5, 2, 16, 1, 7, 3, 12, 9, 20, 28..."
Father's occupation,46,"[10, 4, 8, 11, 6, 9, 5, 2, 3, 22, 7, 1, 12, 39..."
Displaced,2,"[1, 0]"
Educational special needs,2,"[0, 1]"
Debtor,2,"[0, 1]"
Tuition fees up to date,2,"[1, 0]"
Gender,2,"[1, 0]"
Scholarship holder,2,"[0, 1]"
International,2,"[0, 1]"
Target,3,"[Dropout, Graduate, Enrolled]"

In [9]:
for column in categorical_columns:
    print(f"\n--- {column} ---")

    category_counts = pd.DataFrame({
        "Count": df[column].value_counts(dropna=False),
        "Percentage": (
            df[column].value_counts(dropna=False, normalize=True) * 100
        ).round(2)
    })

    display(category_counts)

--- Marital status ---

                Count  Percentage
Marital status
1                3919       88.58
2                 379        8.57
4                  91        2.06
5                  25        0.57
6                   6        0.14
3                   4        0.09

--- Application mode ---

                  Count  Percentage
Application mode
1                  1708       38.61
8                   872       19.71
12                  785       17.74
14                  312        7.05
15                  213        4.81
4                   139        3.14
9                   124        2.80
13                   77        1.74
16                   59        1.33
7                    38        0.86
17                   35        0.79
6                    30        0.68
3                    16        0.36
5                    10        0.23
2                     3        0.07
18                    1        0.02
10                    1        0.02
11                    1        0.02

--- Course ---

        Count  Percentage
Course
12        766       17.31
9         380        8.59
10        355        8.02
6         337        7.62
15        331        7.48
17        268        6.06
14        268        6.06
11        252        5.70
5         226        5.11
2         215        4.86
3         215        4.86
4         210        4.75
16        192        4.34
7         170        3.84
8         141        3.19
13         86        1.94
1          12        0.27

--- Daytime/evening attendance ---

                            Count  Percentage
Daytime/evening attendance
1                            3941       89.08
0                             483       10.92

--- Previous qualification ---

                        Count  Percentage
Previous qualification
1                        3717       84.02
14                        219        4.95
12                        162        3.66
3                         126        2.85
9                          45        1.02
15                         40        0.90
16                         36        0.81
2                          23        0.52
6                          16        0.36
7                          11        0.25
4                           8        0.18
13                          7        0.16
17                          6        0.14
8                           4        0.09
11                          2        0.05
5                           1        0.02
10                          1        0.02

--- Nationality ---

             Count  Percentage
Nationality
1             4314       97.51
14              38        0.86
12              14        0.32
3               13        0.29
9               13        0.29
10               5        0.11
18               3        0.07
4                3        0.07
16               3        0.07
15               2        0.05
11               2        0.05
8                2        0.05
17               2        0.05
2                2        0.05
19               2        0.05
5                1        0.02
13               1        0.02
21               1        0.02
20               1        0.02
6                1        0.02
7                1        0.02

--- Mother's qualification ---

                        Count  Percentage
Mother's qualification
1                        1069       24.16
22                       1009       22.81
13                        953       21.54
23                        562       12.70
3                         438        9.90
19                        130        2.94
2                          83        1.88
4                          49        1.11
10                         42        0.95
5                          21        0.47
25                          9        0.20
7                           8        0.18
24                          8        0.18
26                          6        0.14
27                          4        0.09
6                           4        0.09
28                          4        0.09
9                           3        0.07
18                          3        0.07
20                          3        0.07
21                          3        0.07
8                           3        0.07
17                          3        0.07
11                          2        0.05
12                          1        0.02
14                          1        0.02
16                          1        0.02
15                          1        0.02
29                          1        0.02

--- Father's qualification ---

                        Count  Percentage
Father's qualification
27                       1209       27.33
14                        968       21.88
1                         904       20.43
28                        702       15.87
3                         282        6.37
24                        112        2.53
2                          68        1.54
4                          39        0.88
10                         38        0.86
29                         20        0.45
5                          18        0.41
9                          10        0.23
26                          8        0.18
7                           5        0.11
30                          5        0.11
12                          4        0.09
16                          4        0.09
21                          4        0.09
20                          3        0.07
18                          2        0.05
25                          2        0.05
31                          2        0.05
33                          2        0.05
8                           2        0.05
6                           2        0.05
15                          1        0.02
11                          1        0.02
13                          1        0.02
32                          1        0.02
17                          1        0.02
34                          1        0.02
23                          1        0.02
19                          1        0.02
22                          1        0.02

--- Mother's occupation ---

                     Count  Percentage
Mother's occupation
10                    1577       35.65
5                      817       18.47
6                      530       11.98
4                      351        7.93
3                      318        7.19
8                      272        6.15
1                      144        3.25
2                      102        2.31
7                       91        2.06
12                      70        1.58
9                       36        0.81
29                      26        0.59
13                      17        0.38
32                      11        0.25
20                       8        0.18
15                       7        0.16
22                       6        0.14
28                       5        0.11
30                       5        0.11
19                       4        0.09
11                       4        0.09
31                       4        0.09
23                       3        0.07
18                       3        0.07
21                       3        0.07
24                       2        0.05
14                       2        0.05
25                       2        0.05
16                       1        0.02
27                       1        0.02
17                       1        0.02
26                       1        0.02

--- Father's occupation ---

                     Count  Percentage
Father's occupation
10                    1010       22.83
8                      666       15.05
6                      516       11.66
5                      386        8.73
4                      384        8.68
9                      318        7.19
11                     266        6.01
7                      242        5.47
3                      197        4.45
2                      134        3.03
1                      128        2.89
12                      65        1.47
13                      19        0.43
44                      15        0.34
29                       8        0.18
36                       8        0.18
43                       6        0.14
35                       5        0.11
39                       4        0.09
16                       4        0.09
26                       3        0.07
31                       3        0.07
42                       3        0.07
40                       3        0.07
21                       3        0.07
30                       2        0.05
41                       2        0.05
45                       2        0.05
37                       2        0.05
20                       2        0.05
15                       2        0.05
17                       2        0.05
22                       1        0.02
19                       1        0.02
46                       1        0.02
34                       1        0.02
24                       1        0.02
23                       1        0.02
28                       1        0.02
25                       1        0.02
32                       1        0.02
38                       1        0.02
27                       1        0.02
18                       1        0.02
14                       1        0.02
33                       1        0.02

--- Displaced ---

           Count  Percentage
Displaced
1           2426       54.84
0           1998       45.16

--- Educational special needs ---

                           Count  Percentage
Educational special needs
0                           4373       98.85
1                             51        1.15

--- Debtor ---

        Count  Percentage
Debtor
0        3921       88.63
1         503       11.37

--- Tuition fees up to date ---

                         Count  Percentage
Tuition fees up to date
1                         3896       88.07
0                          528       11.93

--- Gender ---

        Count  Percentage
Gender
0        2868       64.83
1        1556       35.17

--- Scholarship holder ---

                    Count  Percentage
Scholarship holder
0                    3325       75.16
1                    1099       24.84

--- International ---

               Count  Percentage
International
0               4314       97.51
1                110        2.49

--- Target ---

          Count  Percentage
Target
Graduate   2209       49.93
Dropout    1421       32.12
Enrolled    794       17.95

In [10]:
numerical_columns = [
    "Application order",
    "Age at enrollment",
    "Curricular units 1st sem (credited)",
    "Curricular units 1st sem (enrolled)",
    "Curricular units 1st sem (evaluations)",
    "Curricular units 1st sem (approved)",
    "Curricular units 1st sem (grade)",
    "Curricular units 1st sem (without evaluations)",
    "Curricular units 2nd sem (credited)",
    "Curricular units 2nd sem (enrolled)",
    "Curricular units 2nd sem (evaluations)",
    "Curricular units 2nd sem (approved)",
    "Curricular units 2nd sem (grade)",
    "Curricular units 2nd sem (without evaluations)",
    "Unemployment rate",
    "Inflation rate",
    "GDP"
]

Q1 = df[numerical_columns].quantile(0.25)
Q3 = df[numerical_columns].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_mask = (
    (df[numerical_columns] < lower_bound) |
    (df[numerical_columns] > upper_bound)
)

outlier_summary = pd.DataFrame({
    "Lower bound": lower_bound,
    "Upper bound": upper_bound,
    "Number of outliers": outlier_mask.sum(),
    "Outlier percentage": (outlier_mask.mean() * 100).round(2)
})

display(
    outlier_summary.sort_values(
        "Number of outliers",
        ascending=False
    )
)

,Lower bound,Upper bound,Number of outliers,Outlier percentage
Curricular units 2nd sem (grade),6.875,17.208333,877,19.82
Curricular units 1st sem (grade),7.400,17.000000,726,16.41
Curricular units 1st sem (credited),0.000,0.000000,577,13.04
Application order,-0.500,3.500000,541,12.23
Curricular units 2nd sem (credited),0.000,0.000000,530,11.98
Age at enrollment,10.000,34.000000,441,9.97
Curricular units 1st sem (enrolled),2.000,10.000000,424,9.58
Curricular units 2nd sem (enrolled),2.000,10.000000,369,8.34
Curricular units 1st sem (without evaluations),0.000,0.000000,294,6.65
Curricular units 2nd sem (without evaluations),0.000,0.000000,282,6.37
Curricular units 1st sem (approved),-1.500,10.500000,180,4.07
Curricular units 1st sem (evaluations),0.000,16.000000,158,3.57
Curricular units 2nd sem (evaluations),0.000,16.000000,109,2.46
Curricular units 2nd sem (approved),-4.000,12.000000,44,0.99
Unemployment rate,2.650,20.650000,0,0.00
Inflation rate,-3.150,6.050000,0,0.00
GDP,-6.935,7.025000,0,0.00